Fix pgloader not setting NOT NULL after migration
For some reason pgloader didn't set NOT NULL for the thumbnails table in
thumbcache schema causing this error when starting the server:

```
wbia.dtool.depcache_table.TableOutOfSyncError: database 'manta' with table 'thumbnails' does not match the code definition; it's likely the database needs upgraded; Current schema: [('thumbnails_rowid', 'integer primary key'), ('images_rowid', 'integer'), ('config_rowid', "integer default '0'::integer"), ('img_extern_uri', 'text'), ('width', 'integer'), ('height', 'integer')] Expected schema: [('thumbnails_rowid', 'integer primary key'), ('images_rowid', 'integer not null'), ('config_rowid', 'integer default 0'), ('img_extern_uri', 'text'), ('width', 'integer'), ('height', 'integer')]
```

Add NOT NULL to all the non primary key fields after pgloader.