Set LC_ALL and LANG to C.UTF-8 in Dockerfile
When running `super_setup.py`:

```
Traceback (most recent call last):
  File "super_setup.py", line 866, in <module>
    main()
  File "super_setup.py", line 862, in main
    cli_group()
  File "/virtualenv/env3/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/virtualenv/env3/lib/python3.6/site-packages/click/core.py", line 760, in main
    _verify_python3_env()
  File "/virtualenv/env3/lib/python3.6/site-packages/click/_unicodefun.py", line 130, in _verify_python3_env
    " mitigation steps.{}".format(extra)
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/python3/ for mitigation steps.

This system supports the C.UTF-8 locale which is recommended. You might be able to resolve your issue by exporting the following environment variables:

    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8
```

So just set the environment variables in the provision Dockerfile.