Fix some gui tests in gui/guiback.py
Error when running `wbia/gui/guiback.py::MainWindowBackend.select_gid:0` test:

```
DOCTEST TRACEBACK
Traceback (most recent call last):
  File "/virtualenv/env3/lib/python3.6/site-packages/xdoctest/doctest_example.py", line 556, in run
    exec(code, test_globals)
  File "<doctest:/wbia/wildbook-ia/wbia/gui/guiback.py::MainWindowBackend.select_gid:0>", line rel: 5, abs: 1390, in <module>
    >>> valid_gids = ibs.get_valid_gids()
NameError: name 'ibs' is not defined
DOCTEST REPRODUCTION
CommandLine:
    pytest /wbia/wildbook-ia/wbia/gui/guiback.py::MainWindowBackend.select_gid:0
/wbia/wildbook-ia/wbia/gui/guiback.py:1390: NameError
```

The following tests don't complete because they wait for user's inputs:

```
wbia/gui/guiback.py::MainWindowBackend.delete_annot:0
wbia/gui/guiback.py::MainWindowBackend.do_group_occurrence_step:0
```

Mock those interaction so the tests can run.