Disable test in wbia/web/test_api.py
`run_test_api` itself doesn't work anyway (as shown in the test) because
`web_instance` is not an `IBEISController` and doesn't have attribute
`get_web_port_via_scan`.  On top of that, pytest doesn't finish unless
ctrl+c is sent.

```
DOCTEST TRACEBACK
Traceback (most recent call last):
  File "/virtualenv/env3/lib/python3.7/site-packages/xdoctest/doctest_example.py", line 612, in run
    checker.check_exception(exc_got, want, runstate)
  File "/virtualenv/env3/lib/python3.7/site-packages/xdoctest/doctest_example.py", line 598, in run
    exec(code, test_globals)
  File "<doctest:/wbia/wildbook-ia/wbia/web/test_api.py::run_test_api:0>", line rel: 3, abs: 92, in <module>
    >>> response = run_test_api()
  File "/wbia/wildbook-ia/wbia/web/test_api.py", line 106, in run_test_api
    web_port = web_instance.get_web_port_via_scan()
AttributeError: 'KillableProcess' object has no attribute 'get_web_port_via_scan'
DOCTEST REPRODUCTION
CommandLine:
    pytest /wbia/wildbook-ia/wbia/web/test_api.py::run_test_api:0
```