Enable wbia_cnn plugin in control/IBEISControl.py
When running doctests:

```
...
  File "/wbia/wildbook-ia/wbia/core_annots.py", line 823, in cnn_probchips
    mask_gen = ibs.generate_species_background_mask(inputchip_fpaths, species)
AttributeError: 'IBEISController' object has no attribute 'generate_species_background_mask'
DOCTEST REPRODUCTION
CommandLine:
    python -m xdoctest /wbia/wildbook-ia/wbia/web/graph_server.py GraphActor:1
```

`generate_species_background_mask` is defined in the wbia cnn plugin.  It needs
to be added to `AUTOLOAD_PLUGIN_MODNAMES` in
`wildbook-ia/wbia/control/IBEISControl.py` for the method to be added.