Fix assertion error message in web/apis_query.py::query_chips
When `qreq_` is `None` and `qaid_list` or `daid_list` is `None`, the
assertion error message is:

```
AssertionError: do not specify daids and qreq
```

but actually the user needs to define `qaid_list` and `daid_list`
because `qreq_` is not defined.