Fix superkey constraint error in create table sql
Fix error if superkeys is None when creating "create table" sql

```
DOCTEST TRACEBACK
Traceback (most recent call last):
  File "/virtualenv/env3/lib/python3.7/site-packages/xdoctest/doctest_example.py", line 598, in run
    exec(code, test_globals)
  File "<doctest:/wbia/wildbook-ia/wbia/control/manual_annot_funcs.py::get_annot_contact_aids:1>", line rel: 4, abs: 1442, in <module>
    >>> ibs = wbia.opendb('testdb2')
  File "/wbia/wildbook-ia/wbia/entry_points.py", line 573, in opendb
    ibs = _init_wbia(dbdir, verbose=verbose, use_cache=use_cache, web=web, **kwargs)
  File "/wbia/wildbook-ia/wbia/entry_points.py", line 92, in _init_wbia
    force_serial=force_serial,
  File "/wbia/wildbook-ia/wbia/control/IBEISControl.py", line 279, in request_IBEISController
    request_stagingversion=request_stagingversion,
  File "/wbia/wildbook-ia/wbia/control/IBEISControl.py", line 369, in __init__
    request_stagingversion=request_stagingversion,
  File "/wbia/wildbook-ia/wbia/control/IBEISControl.py", line 601, in _init_sql
    ibs._init_sqldbcore(request_dbversion=request_dbversion)
  File "/wbia/wildbook-ia/wbia/control/IBEISControl.py", line 696, in _init_sqldbcore
    dobackup=not ibs.readonly,
  File "/wbia/wildbook-ia/wbia/control/_sql_helpers.py", line 340, in ensure_correct_version
    ibs, db, schema_spec, version, version_expected, dobackup=dobackup
  File "/wbia/wildbook-ia/wbia/control/_sql_helpers.py", line 431, in update_schema_version
    update(db, ibs=ibs)
  File "/wbia/wildbook-ia/wbia/control/DB_SCHEMA.py", line 1332, in update_1_4_3
    (None, 'annotmatch_is_nondistinct', 'INTEGER', None),
  File "/wbia/wildbook-ia/wbia/dtool/sql_control.py", line 1839, in modify_table
    self.add_table(tablename_temp, coldef_list, **metadata_keyval2)
  File "/wbia/wildbook-ia/wbia/dtool/sql_control.py", line 1665, in add_table
    operation = self._make_add_table_sqlstr(tablename, coldef_list, **metadata_keyval)
  File "/wbia/wildbook-ia/wbia/dtool/sql_control.py", line 1645, in _make_add_table_sqlstr
    self.__make_unique_constraint(x) for x in metadata_keyval.get('superkeys', [])
TypeError: 'NoneType' object is not iterable
DOCTEST REPRODUCTION
CommandLine:
    pytest /wbia/wildbook-ia/wbia/control/manual_annot_funcs.py::get_annot_contact_aids:1
```

Fix error superkey constraint in create table sql

When modifying tables in a migration, the create table sql generated
returns an error:

```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "encounter_rowid": syntax error
[SQL: CREATE TABLE IF NOT EXISTS encounter_image_relationship_temp1fedefaa ( egr_rowid INTEGER PRIMARY KEY, image_rowid INTEGER NOT NULL, encounter_rowid INTEGER, CONSTRAINT unique_image_rowid, encounter_rowid UNIQUE (image_rowid, encounter_rowid) )]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
DOCTEST REPRODUCTION
CommandLine:
    pytest /wbia/wildbook-ia/wbia/control/manual_annot_funcs.py::get_annot_thetas:0
```

This was caused by table metadata returning
`[('image_rowid, encounter_rowid',)]` as the superkeys value instead of
`[('image_rowid',), ('encounter_rowid',)]`.