Require matplotlib>=3.3.0 (current version)
An older matplotlib (for example 3.0.2) is incompatible with a newer
Pillow (> 7.0.0) because in older versions, matplotlib looks for
`PILLOW_VERSION` which got removed in Pillow 7.0.0, causing `jpg` to not
be supported:

```
DOCTEST TRACEBACK
Traceback (most recent call last):
  File "/virtualenv/env3/lib/python3.6/site-packages/xdoctest/doctest_example.py", line 556, in run
    exec(code, test_globals)
  File "<doctest:/wbia/wildbook-ia/wbia/gui/id_review_api.py::make_ensure_match_img_nosql_func:0>", line rel: 10, abs: 674, in <module>
    >>> match_thumb_fpath_ = ensure_match_img(qreq_.ibs, cm, daid, qreq_, match_thumbtup_cache)
  File "/wbia/wildbook-ia/wbia/gui/id_review_api.py", line 629, in ensure_match_img
    verbose=False,
  File "/wbia/wildbook-ia/wbia/algo/hots/chip_match.py", line 629, in imwrite_single_annotmatch
    img_fpath = pt.save_figure(fpath=fpath, fig=fig, **savekw)
  File "/wbia/wildbook-ia/wbia/plottool/custom_figure.py", line 455, in save_figure
    fig.savefig(fpath_clean, **savekw)
  File "/virtualenv/env3/lib/python3.6/site-packages/matplotlib/figure.py", line 2094, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/virtualenv/env3/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 88, in print_figure
    super().print_figure(*args, **kwargs)
  File "/virtualenv/env3/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2006, in print_figure
    canvas = self._get_output_canvas(format)
  File "/virtualenv/env3/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 1948, in _get_output_canvas
    .format(fmt, ", ".join(sorted(self.get_supported_filetypes()))))
ValueError: Format 'jpg' is not supported (supported formats: eps, pdf, pgf, png, ps, raw, rgba, svg, svgz)
DOCTEST REPRODUCTION
CommandLine:
    pytest /wbia/wildbook-ia/wbia/gui/id_review_api.py::make_ensure_match_img_nosql_func:0
```