Use manylinux2014 in python-publish github workflow
The github workflow python-publish has been failing with:

```
Collecting pyqt5; python_version > "2.7"
  Downloading PyQt5-5.15.0.tar.gz (3.3 MB)
  Installing build dependencies: started
  ...
      File "/tmp/pip-build-env-m18u7_2p/overlay/lib/python3.5/site-packages/sipbuild/project.py", line 223, in apply_user_defaults
        self.builder.apply_user_defaults(tool)
      File "/tmp/pip-build-env-m18u7_2p/overlay/lib/python3.5/site-packages/pyqtbuild/builder.py", line 68, in apply_user_defaults
        "specify a working qmake or add it to PATH")
    sipbuild.pyproject.PyProjectOptionException
    ----------------------------------------
ERROR: Command errored out with exit status 1: /tmp/tmp.3b2jWWR7pY/venv/bin/python /tmp/tmp.3b2jWWR7pY/venv/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpb7jvscte Check the logs for full command output.
```

This is because https://pypi.org/project/PyQt5/#files only provides wheels for
manylinux2014 and by default, cibuildwheel uses manylinux2010 so we couldn't
download the wheel.