Fix from_items AttributeError in algo/graph/mixin_groundtruth.py
When running the test `wbia/algo/graph/refresh.py::demo_refresh:0`:

```
Traceback (most recent call last):
  File "/virtualenv/env3/lib/python3.6/site-packages/xdoctest/doctest_example.py", line 556, in run
    exec(code, test_globals)
  File "<doctest:/wbia/wildbook-ia/wbia/algo/graph/refresh.py::demo_refresh:0>", line rel: 3, abs: 218, in <module>
    >>> demo_refresh()
  File "/wbia/wildbook-ia/wbia/algo/graph/refresh.py", line 232, in demo_refresh
    ys = infr.match_state_df(edges)[POSTV].values
  File "/wbia/wildbook-ia/wbia/algo/graph/mixin_groundtruth.py", line 56, in match_state_df
    match_state_df = pd.DataFrame.from_items(
AttributeError: type object 'DataFrame' has no attribute 'from_items'
```

Looking at the panda changelog, it seems `from_items` was removed in
`v1.0.0` and replaced by `from_dict`.

See https://github.com/pandas-dev/pandas/pull/18529.