Fix guitool import in init/sysres.py
When running doctests:

```
DOCTEST TRACEBACK
Traceback (most recent call last):
  File "/virtualenv/env3/lib/python3.6/site-packages/xdoctest/doctest_example.py", line 553, in run
    exec(code, test_globals)
  File "<doctest:/wbia/wildbook-ia/wbia/gui/id_review_api.py::make_ensure_match_img_nosql_func:0>", line rel: 5, abs: 669, in <module>
    >>> cm, qreq_ = wbia.testdata_cm()
  File "/wbia/wildbook-ia/wbia/init/main_helpers.py", line 524, in testdata_cm
    a=a,
  File "/wbia/wildbook-ia/wbia/init/main_helpers.py", line 494, in testdata_cmlist
    a=a,
  File "/wbia/wildbook-ia/wbia/init/main_helpers.py", line 451, in testdata_qreq_
    **kwargs,
  File "/wbia/wildbook-ia/wbia/init/main_helpers.py", line 342, in testdata_expanded_aids
    ibs = wbia.opendb(defaultdb=defaultdb)
  File "/wbia/wildbook-ia/wbia/main_module.py", line 594, in opendb
    defaultdb=defaultdb, allow_newdir=allow_newdir, db=db, dbdir=dbdir
  File "/wbia/wildbook-ia/wbia/init/sysres.py", line 346, in get_args_dbdir
    return db_to_dbdir(defaultdb, allow_newdir=allow_newdir)
  File "/wbia/wildbook-ia/wbia/init/sysres.py", line 219, in db_to_dbdir
    work_dir = get_workdir()
  File "/wbia/wildbook-ia/wbia/init/sysres.py", line 92, in get_workdir
    work_dir = set_workdir()
  File "/wbia/wildbook-ia/wbia/init/sysres.py", line 121, in set_workdir
    work_dir = guiselect_workdir()
  File "/wbia/wildbook-ia/wbia/init/sysres.py", line 156, in guiselect_workdir
    guitool.ensure_qtapp()
NameError: name 'guitool' is not defined
```

This is because we imported guitool like this `import wbia.guitool`, instead I
changed it to `from wbia import guitool`.