Handle duplicate columns in SQLDatabaseController.get_where
Specifically, this test was failing:

```
DOCTEST TRACEBACK
Traceback (most recent call last):
  File "/virtualenv/env3/lib/python3.7/site-packages/xdoctest/doctest_example.py", line 598, in run
    exec(code, test_globals)
  File "<doctest:/wbia/wildbook-ia/wbia/dtool/depcache_table.py::DependencyCacheTable.get_row_data:0>", line rel: 10, abs: 2585, in <module>
    >>> prop_list = table.get_row_data(tbl_rowids, colnames, **kwargs)
  File "/wbia/wildbook-ia/wbia/dtool/depcache_table.py", line 2741, in get_row_data
    tries_left,
  File "/wbia/wildbook-ia/wbia/dtool/depcache_table.py", line 2794, in _resolve_any_external_data
    for uri in prop_listT[extern_colx]:
IndexError: list index out of range
DOCTEST REPRODUCTION
CommandLine:
    pytest /wbia/wildbook-ia/wbia/dtool/depcache_table.py::DependencyCacheTable.get_row_data:0
/wbia/wildbook-ia/wbia/dtool/depcache_table.py:2585: IndexError
```

The test was getting `size_1`, `size_0`, `size_1`, `chip_extern_uri`,
`chip_extern_uri` from the `chip` table.  SQLAlchemy generated sql that looks
like:

```
SELECT chip.size_1, chip.size_0, chip.chip_extern_uri
FROM chip
WHERE chip_rowid = :_identifier
```

removing all the duplicate columns, causing the `IndexError` above.