Fix AttributeError selfloop_edges in test_neg_metagraph.py
When running the test `test_neg_metagraph_merge`:

```
>       assert len(list(nmg.selfloop_edges())) == 1
E       AttributeError: 'NiceGraph' object has no attribute 'selfloop_edges'
```

This is because networkx has moved some methods from the base graph class into
the main namespace.  See
https://networkx.github.io/documentation/stable/release/migration_guide_from_1.x_to_2.0.html.

So need to change

```
nmg.selfloop_edges()
```

to

```
nx.selfloop_edges(nmg)
```