Fix guitool import in guitool/api_item_model.py doctests
When running the wildbook-ia doctests:

```
--- Error: 117 / 117 ---
    * REASON: NameError
    DOCTEST DEBUG INFO
      XDoc "/wbia/wildbook-ia/wbia/guitool/api_item_model.py::simple_thumbnail_widget:0", line 4 <- wrt doctest
      File "/wbia/wildbook-ia/wbia/guitool/api_item_model.py", line 1086, <- wrt source file
    DOCTEST PART BREAKDOWN
    Failed Part:
        1 >>> # ENABLE_DOCTEST
        2 >>> import wbia.guitool
        3 >>> from wbia.guitool.api_item_model import *  # NOQA
        4 >>> guitool.ensure_qapp()  # must be ensured before any embeding
        5 >>> wgt = simple_thumbnail_widget()
        6 >>> ut.quit_if_noshow()
        7 >>> wgt.show()
        8 >>> guitool.qtapp_loop(wgt, frequency=100, init_signals=True)
    DOCTEST TRACEBACK
    Traceback (most recent call last):

      File "/virtualenv/env3/lib/python3.6/site-packages/xdoctest/doctest_example.py", line 553, in run
        exec(code, test_globals)

      File "<doctest:/wbia/wildbook-ia/wbia/guitool/api_item_model.py::simple_thumbnail_widget:0>", line rel: 4, abs: 1086, in <module>
        >>> guitool.ensure_qapp()  # must be ensured before any embeding

    NameError: name 'guitool' is not defined
    DOCTEST REPRODUCTION
    CommandLine:
        python -m xdoctest /wbia/wildbook-ia/wbia/guitool/api_item_model.py simple_thumbnail_widget:0
```

It's because we probably changed `import guitool` to
`import wbia.guitool` and now `guitool` is not defined.  Changing to
`import wbia.guitool as guitool` works.