Revert ibeis->wbia filename changes for backwards compatibility
When running `python _dev/reset_dbs.py`:

```
Traceback (most recent call last):
  File "../_dev/reset_dbs.py", line 14, in <module>
    reset_testdbs.reset_testdbs()
  File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/wbia/tests/reset_testdbs.py", line 181, in reset_testdbs
    wbia.ensure_pz_mtest()
  File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/wbia/init/sysres.py", line 425, in ensure_pz_mtest
    ibs = wbia.opendb('PZ_MTEST')
  File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/wbia/main_module.py", line 600, in opendb
    ibs = _init_wbia(dbdir, verbose=verbose, use_cache=use_cache, web=web, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/wbia/main_module.py", line 113, in _init_wbia
    force_serial=force_serial,
  File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/wbia/control/IBEISControl.py", line 254, in request_IBEISController
    dbdir, ensure=ensure, wbaddr=wbaddr, verbose=verbose
  File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/wbia/dbio/ingest_hsdb.py", line 335, in convert_hsdb_to_wbia
    assert len(ibs.get_valid_gids()) == 0, 'target database is not empty'
AssertionError: target database is not empty
```

This is because the hsdb has already been converted in the files downloaded
during `reset_dbs.py`.  But because we changed the `SUCCESS_FLAG_FNAME` in
`wbia/dbio/ingest_hsdb.py`, this couldn't be detected and the code tries to
convert the database again.

We need to have some kind of backwards compatibility code and possibly
migrations for all existing databases before attempting this again.

Partial revert of commit 42321675d0 "Small fixes for migrations":

```
git show 42321675d0 wbia/dbio/export_hsdb.py wbia/dbio/ingest_hsdb.py >a.diff
patch -p1 --reverse <a.diff
```