Change column names to lowercase when inserting in postgres
Postgres table column names are lowercase causing `SQLDatabaseController._add`
to fail because the parameterized values do not match the column names expected
by the insert statement:

```
DOCTEST TRACEBACK
Traceback (most recent call last):
  File "/virtualenv/env3/lib/python3.7/site-packages/xdoctest/doctest_example.py", line 598, in run
    exec(code, test_globals)
  File "<doctest:/wbia/wildbook-ia/wbia/_wbia_object.py::ObjectView1D:0>", line rel: 9, abs: 525, in <module>
    >>> assert np.all(v.vecs[0] == v.vecs[1])
  File "/wbia/wildbook-ia/wbia/_wbia_object.py", line 567, in __getattr__
    miss_data = _rowid_getter(miss_rowids)
  File "/wbia/wildbook-ia/wbia/_wbia_object.py", line 160, in _rowid_getter
    data = ibs_callable(rowids, config2_=self._config)
  File "/wbia/wbia-utool/utool/util_decor.py", line 556, in wrp_asivo
    return func(self, input_, *args, **kwargs)
  File "/wbia/wildbook-ia/wbia/control/accessor_decors.py", line 487, in getter_vector_wrp
    return func(*args, **kwargs)
  File "/wbia/wildbook-ia/wbia/control/manual_feat_funcs.py", line 176, in get_annot_vecs
    'feat', aid_list, 'vecs', config=config2_, ensure=ensure, eager=eager
  File "/wbia/wbia-utool/utool/util_decor.py", line 489, in wrp_asi2
    return func(self, *args, **kwargs)
  File "/wbia/wildbook-ia/wbia/dtool/depcache_control.py", line 885, in get
    tbl_rowids = self.get_rowids(tablename, input_tuple, **rowid_kw)
  File "/wbia/wildbook-ia/wbia/dtool/depcache_control.py", line 722, in get_rowids
    **_kwargs,
  File "/wbia/wildbook-ia/wbia/dtool/depcache_control.py", line 634, in get_parent_rowids
    _parent_rowids, config=config_, recompute=_recompute, **_kwargs
  File "/wbia/wildbook-ia/wbia/dtool/depcache_table.py", line 2377, in get_rowid
    config=config,
  File "/wbia/wildbook-ia/wbia/dtool/depcache_table.py", line 2155, in ensure_rows
    nInput=nChunkInput,
  File "/wbia/wildbook-ia/wbia/dtool/sql_control.py", line 954, in _add
    result = self.connection.execute(insert_stmt.values(vals))
  File "/virtualenv/env3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/virtualenv/env3/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/virtualenv/env3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1121, in _execute_clauseelement
    else None,
  File "<string>", line 1, in <lambda>
  File "/virtualenv/env3/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 481, in compile
    return self._compiler(dialect, bind=bind, **kw)
  File "/virtualenv/env3/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 487, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/virtualenv/env3/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 592, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/virtualenv/env3/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 322, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/virtualenv/env3/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 352, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/virtualenv/env3/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 96, in _compiler_dispatch
    return meth(self, **kw)
  File "/virtualenv/env3/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 2430, in visit_insert
    self, insert_stmt, crud.ISINSERT, **kw
  File "/virtualenv/env3/lib/python3.7/site-packages/sqlalchemy/sql/crud.py", line 64, in _setup_crud_params
    return _get_crud_params(compiler, stmt, **kw)
  File "/virtualenv/env3/lib/python3.7/site-packages/sqlalchemy/sql/crud.py", line 179, in _get_crud_params
    % (", ".join("%s" % c for c in check))
sqlalchemy.exc.CompileError: Unconsumed column names: M
DOCTEST REPRODUCTION
CommandLine:
    pytest /wbia/wildbook-ia/wbia/_wbia_object.py::ObjectView1D:0
```