Change wbia to ibeis in hsdb convert success flag filename
We previously changed the filename to `_hsdb_to_wbia_convert_success`.
This became a problem when running `dev/reset_dbs.py`:

```
Traceback (most recent call last):
  File "dev/reset_dbs.py", line 14, in <module>
    reset_testdbs.reset_testdbs()
  File "/wbia/wildbook-ia/wbia/tests/reset_testdbs.py", line 181, in reset_testdbs
    wbia.ensure_pz_mtest()
  File "/wbia/wildbook-ia/wbia/init/sysres.py", line 425, in ensure_pz_mtest
    ibs = wbia.opendb('PZ_MTEST')
  File "/wbia/wildbook-ia/wbia/main_module.py", line 601, in opendb
    ibs = _init_wbia(dbdir, verbose=verbose, use_cache=use_cache, web=web, **kwargs)
  File "/wbia/wildbook-ia/wbia/main_module.py", line 113, in _init_wbia
    force_serial=force_serial,
  File "/wbia/wildbook-ia/wbia/control/IBEISControl.py", line 254, in request_IBEISController
    dbdir, ensure=ensure, wbaddr=wbaddr, verbose=verbose
  File "/wbia/wildbook-ia/wbia/dbio/ingest_hsdb.py", line 337, in convert_hsdb_to_wbia
    assert len(ibs.get_valid_gids()) == 0, 'target database is not empty'
AssertionError: target database is not empty
```

The code couldn't detect that the database doesn't need to be converted
because the filename changed, so change it back to
`_hsdb_to_ibeis_convert_success`.