Fix algo/detect/assigner.py assigner_feat_for_aids test
```
DOCTEST TRACEBACK
Traceback (most recent call last):

  File "/virtualenv/env3/lib/python3.7/site-packages/xdoctest/doctest_example.py", line 598, in run
    exec(code, test_globals)

  File "<doctest:/wbia/wildbook-ia/wbia/algo/detect/assigner.py::assigner_feat_for_aids:0>", line rel: 7, abs: 430, in <module>
    >>> result = assigner_feat_for_aids(aids)

TypeError: assigner_feat_for_aids() missing 1 required positional argument: 'aid_list'
DOCTEST REPRODUCTION
CommandLine:
    pytest /wbia/wildbook-ia/wbia/algo/detect/assigner.py::assigner_feat_for_aids:0
/wbia/wildbook-ia/wbia/algo/detect/assigner.py:430: TypeError
```