Limit scikit-learn to >=0.24.0 and <1.0
Upgrading scikit-learn to 1.0 caused segmentation fault in CI with
python 3.7 (but 3.8 is ok):

```
=========================== short test summary info ============================
SKIPPED [590] ../../../../../opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/xdoctest/plugin.py:172: doctest encountered global skip directive
SKIPPED [25] ../../../../../opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/xdoctest/doctest_example.py:768: Skipped
========= 726 passed, 615 skipped, 6116 warnings in 3349.86s (0:55:49) =========
Fatal Python error: Segmentation fault

Current thread 0x00007fbd9a4c9740 (most recent call first):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pyflann/index.py", line 489 in delete_index
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pyflann/index.py", line 152 in __del__
/home/runner/work/_temp/2426ca9f-7f07-44a5-8528-9c8c330cd684.sh: line 3:  3712 Segmentation fault      (core dumped) pytest --slow --web-tests --with-postgres-uri=$POSTGRES_URI
Error: Process completed with exit code 139.
```