Fix cv2.so symlink in dependencies dockerfile
When we upgraded opencv 3.4.4 to 3.4.10, for some reason, the so file
has moved from:

```
/virtualenv/env3/python/cv2/python-3.6/cv2.cpython-36m-x86_64-linux-gnu.so
```

to

```
/virtualenv/env3/lib/python3.6/site-packages/cv2/python-3.6/cv2.cpython-36m-x86_64-linux-gnu.so
```

Because the symlink was broken, we couldn't import anything from cv2:

```
>>> import cv2
>>> cv2.INTER_NEAREST
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'cv2' has no attribute 'INTER_NEAREST'
>>> cv2.__spec__
ModuleSpec(name='cv2', loader=None, origin='namespace', submodule_search_locations=_NamespacePath(['/virtualenv/env3/lib/python3.6/site-packages/cv2', '/virtualenv/env3/lib/python3.6/site-packages/cv2']))
```