Update algo/verif/clf_helpers.py to use latest sklearn APIs
First error, `sklearn.preprocessing.Imputer` has been removed in v0.22
and has become `sklearn.impute.SimpleImputer`:

```
  File "/wbia/wildbook-ia/wbia/algo/verif/clf_helpers.py", line 398, in clf_partial
    sklearn.preprocessing.Imputer(
AttributeError: module 'sklearn.preprocessing' has no attribute 'Imputer'
```

`sklearn.impute.SimpleImputer` doesn't accept the keyword argument "axis"
anymore.  In the code "axis" is set to 0, so we can just remove it:

```
  File "/wbia/wildbook-ia/wbia/algo/verif/clf_helpers.py", line 400, in clf_partial
    missing_values='NaN', strategy='mean', axis=0
  File "/virtualenv/env3/lib/python3.6/site-packages/scikit_learn-0.23.1-py3.6-linux-x86_64.egg/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'axis'
```

`sklearn.impute.SimpleImputer` has a default value for `missing_values` which
is `np.nan` instead of `NaN` in the older version.  Since the default value is
what we want, we can just remove `missing_values` when initializing
`SimpleImputer`:

```
  File "/wbia/wildbook-ia/wbia/algo/verif/clf_helpers.py", line 132, in learn_evaluation_classifiers
    pblm._ensure_evaluation_clf(task_key, data_key, clf_key)
  File "/wbia/wildbook-ia/wbia/algo/verif/clf_helpers.py", line 177, in _ensure_evaluation_clf
    data = pblm._train_evaluation_clf(task_key, data_key, clf_key)
  File "/wbia/wildbook-ia/wbia/algo/verif/clf_helpers.py", line 227, in _train_evaluation_clf
    clf.fit(X_train, y_train)
  File "/virtualenv/env3/lib/python3.6/site-packages/scikit_learn-0.23.1-py3.6-linux-x86_64.egg/sklearn/pipeline.py", line 330, in fit
    Xt = self._fit(X, y, **fit_params_steps)
  File "/virtualenv/env3/lib/python3.6/site-packages/scikit_learn-0.23.1-py3.6-linux-x86_64.egg/sklearn/pipeline.py", line 296, in _fit
    **fit_params_steps[name])
  File "/virtualenv/env3/lib/python3.6/site-packages/joblib-0.16.0-py3.6.egg/joblib/memory.py", line 352, in __call__
    return self.func(*args, **kwargs)
  File "/virtualenv/env3/lib/python3.6/site-packages/scikit_learn-0.23.1-py3.6-linux-x86_64.egg/sklearn/pipeline.py", line 740, in _fit_transform_one
    res = transformer.fit_transform(X, y, **fit_params)
  File "/virtualenv/env3/lib/python3.6/site-packages/scikit_learn-0.23.1-py3.6-linux-x86_64.egg/sklearn/base.py", line 693, in fit_transform
    return self.fit(X, y, **fit_params).transform(X)
  File "/virtualenv/env3/lib/python3.6/site-packages/scikit_learn-0.23.1-py3.6-linux-x86_64.egg/sklearn/impute/_base.py", line 277, in fit
    X = self._validate_input(X, in_fit=True)
  File "/virtualenv/env3/lib/python3.6/site-packages/scikit_learn-0.23.1-py3.6-linux-x86_64.egg/sklearn/impute/_base.py", line 253, in _validate_input
    _check_inputs_dtype(X, self.missing_values)
  File "/virtualenv/env3/lib/python3.6/site-packages/scikit_learn-0.23.1-py3.6-linux-x86_64.egg/sklearn/impute/_base.py", line 28, in _check_inputs_dtype
    .format(X.dtype, type(missing_values)))
ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.
```