Change print statements to logger.info
```
cat >add-logging.sed
:a
/^\(from\|import\)/! {p; n; ba}
/^\(from\|import\)/ {
x
i import logging
g
p
:b
n
p
bb
}
```

```
git grep -l '.inject2(' '*.py' | xargs sed -i -e '/.inject2(/ a logger = logging.getLogger()' -e '/ut.inject2/,$ s/^\([ #]*\)print(/\1logger.info(/'
git grep -l '.inject2(' '*.py' | xargs sed -i -n -f add-logging.sed
```

and fix flake8 errors:

```
wbia/gui/inspect_gui.py:137:13: F823 local variable 'logger' defined in enclosing scope on line 28 referenced before assignment
wbia/gui/inspect_gui.py:527:13: F823 local variable 'logger' defined in enclosing scope on line 28 referenced before assignment
wbia/web/app.py:8:1: F811 redefinition of unused 'logging' from line 5
wbia/web/app.py:150:17: F823 local variable 'logger' defined in enclosing scope on line 18 referenced before assignment
wbia/algo/graph/core.py:30:1: F811 redefinition of unused 'logging' from line 2
wbia/algo/preproc/occurrence_blackbox.py:35:10: F821 undefined name 'logging'
wbia/web/job_engine.py:511:9: F841 local variable 'print' is assigned to but never used
wbia/web/job_engine.py:654:9: F841 local variable 'print' is assigned to but never used
wbia/web/job_engine.py:885:13: F841 local variable 'print' is assigned to but never used
wbia/web/job_engine.py:946:13: F841 local variable 'print' is assigned to but never used
wbia/web/job_engine.py:958:13: F841 local variable 'print' is assigned to but never used
wbia/web/job_engine.py:970:13: F841 local variable 'print' is assigned to but never used
wbia/web/job_engine.py:982:13: F841 local variable 'print' is assigned to but never used
wbia/web/job_engine.py:995:17: F841 local variable 'print' is assigned to but never used
wbia/web/job_engine.py:1056:9: F841 local variable 'print' is assigned to but never used
```