Build wheels only for cp >= 3.6 in github workflow
```
Collecting brambox
  Downloading brambox-2.0.0.tar.gz (194 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/tmp.vAFWmU1mUs/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-eeeti1j3/brambox/setup.py'"'"'; __file__='"'"'/tmp/pip-install-eeeti1j3/brambox/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-znfaqa9i
         cwd: /tmp/pip-install-eeeti1j3/brambox/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-eeeti1j3/brambox/setup.py", line 28
        f.write(f'__version__ = "{version}')
                                          ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

This is because the newest version of brambox that supports python 3.5 is
2.0.0.  The latest version 3.0.0 only supports python >=3.6.