Create Affine2D objects only if necessary in plottool/mpl_sift.py
When running `pytest wbia/plottool/mpl_keypoint.py::draw_keypoints:0`:

```
DOCTEST TRACEBACK
Traceback (most recent call last):
  File "/virtualenv/env3/lib/python3.6/site-packages/xdoctest/doctest_example.py", line 556, in run
    exec(code, test_globals)
  File "<doctest:/wbia/wildbook-ia/wbia/plottool/mpl_keypoint.py::draw_keypoints:0>", line rel: 31, abs: 107, in <module>
    ...                rect, eig, ori, sifts, siftkw, H=H, **kwargs)
  File "/wbia/wildbook-ia/wbia/plottool/mpl_keypoint.py", line 163, in draw_keypoints
    mpl_sift.draw_sifts(ax, sifts, invVR_aff2Ds, **siftkw)
  File "/wbia/wildbook-ia/wbia/plottool/mpl_sift.py", line 280, in draw_sifts
    invVR_aff2Ds = [mpl.transforms.Affine2D(matrix=aff_) for aff_ in invVR_aff2Ds]
  File "/wbia/wildbook-ia/wbia/plottool/mpl_sift.py", line 280, in <listcomp>
    invVR_aff2Ds = [mpl.transforms.Affine2D(matrix=aff_) for aff_ in invVR_aff2Ds]
  File "/virtualenv/env3/lib/python3.6/site-packages/matplotlib/transforms.py", line 1846, in __init__
    self._mtx = matrix.copy()
AttributeError: 'Affine2D' object has no attribute 'copy'
```

It seems that `aff_` is already a `Affine2D` object, and that's causing the
failure, so check before creating `Affine2D` objects.