Ignore docker error if wbia_deepsense is unavailable
After docker 4.3.1 is released, we are getting errors when running the
smoke test:

```
VTOOL BACKEND FOR pyflann = <module 'pyflann' from '/wildbook-ia/py3/lib64/python3.6/site-packages/pyflann/__init__.py'>
VTOOL BACKEND FOR FLANN_CLS = <class 'pyflann.index.FLANN'>
[pydarknet] CPU fallback for: pydarknet_cuda
Local docker client is not available

+------

<!!! EXCEPTION !!!>

...

Traceback (most recent call last):
  File "/wildbook-ia/py3/lib64/python3.6/site-packages/wbia/__init__.py", line 53, in <module>
    from wbia import other
  File "/wildbook-ia/py3/lib64/python3.6/site-packages/wbia/other/__init__.py", line 6, in <module>
    from wbia.other import detectgrave
  File "/wildbook-ia/py3/lib64/python3.6/site-packages/wbia/other/detectgrave.py", line 17, in <module>
    from wbia.control import controller_inject
  File "/wildbook-ia/py3/lib64/python3.6/site-packages/wbia/control/__init__.py", line 11, in <module>
    from wbia.control import IBEISControl
  File "/wildbook-ia/py3/lib64/python3.6/site-packages/wbia/control/IBEISControl.py", line 161, in <module>
    ub.import_module_from_name(modname)
  File "/wildbook-ia/py3/lib64/python3.6/site-packages/ubelt/util_import.py", line 260, in import_module_from_name
    module = importlib.import_module(modname)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/wildbook-ia/py3/lib64/python3.6/site-packages/wbia/control/docker_control.py", line 17, in <module>
    raise RuntimeError('Failed to connect to Docker for Deepsense Plugin')
RuntimeError: Failed to connect to Docker for Deepsense Plugin
```

It seems that docker has to be running / available to be connected to avoid this error.

Since it's used for deepsense, we can ignore it if `wbia_deepsense` is
not available.