Clean up after annotmatch_funcs.py test
After running test
`wbia/annotmatch_funcs.py::set_annot_pair_as_negative_match:0`, the
database was changed causing another test
`wbia/control/manual_name_funcs.py::get_empty_nids:0` to fail:

```
DOCTEST TRACEBACK
Traceback (most recent call last):
  File "/virtualenv/env3/lib/python3.6/site-packages/xdoctest/doctest_example.py", line 556, in run
    exec(code, test_globals)
  File "<doctest:/wbia/wildbook-ia/wbia/control/manual_name_funcs.py::get_empty_nids:0>", line rel: 7, abs: 233, in <module>
    >>> assert len(empty_nids) == 2, 'get_empty_nids fails1'
AssertionError: get_empty_nids fails1
```

Clean up by removing the created `nid` in `set_annot_pair_as_negative_match:0`
test.