Fix wbia/web/apis_engine.py::start_identify_annots:2 test
Add expected output to wbia/web/apis_engine.py::start_identify_annots:2
test so we can assert the job actually completed.

The job ended with an exception originally:

```
<!!! EXCEPTION !!!>
Traceback (most recent call last):                                                                                                                   File "/wbia/wildbook-ia/wbia/web/job_engine.py", line 1472, in on_engine_request
    result = action_func(*args, **kwargs)
  File "/wbia/wildbook-ia/wbia/web/apis_query.py", line 116, in query_chips_simple_dict
    return ibs.query_chips(*args, **kwargs)
TypeError: query_chips() got an unexpected keyword argument \'__jobid__\'

[!on_engine_request] [!?] Caught exception
<class \'TypeError\'>: query_chips() got an unexpected keyword argument \'__jobid__\'
[!on_engine_request] jobid = \'3a768a89-c0e6-49d6-aca1-0bc10abdbd40\'
</!!! EXCEPTION !!!>
```

Change `wbia/web/job_engine.py` `on_engine_request` to not add
`__jobid__` to the keyword arguments if this error is returned.  (I'm
not sure why `__jobid__` is added at all.)

This fixes the exception and allows the job to complete.