Testing and rewriting get_where_eq with SQLAlchemy
Corrects the following traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/xdoctest/doctest_example.py", line 571, in run
    exec(code, test_globals)
  File "<doctest:/code/wbia/dtool/sql_control.py::SQLDatabaseController.add_cleanly:0>", line rel: 28, abs: 833, in <module>
    >>>     tblname, colnames, params_iter, get_rowid_from_superkey, superkey_paramx)
  File "/code/wbia/dtool/sql_control.py", line 853, in add_cleanly
    rowid_list_ = get_rowid_from_superkey(*superkey_lists)
  File "<doctest:/code/wbia/dtool/sql_control.py::SQLDatabaseController.add_cleanly:0>", line rel: 26, abs: 831, in get_rowid_from_superkey
    >>>     return db.get_where_eq(tblname, ('rowid',), zip(superkeys_list), superkey_colnames)
  File "/code/wbia/dtool/sql_control.py", line 930, in get_where_eq
    **kwargs,
  File "/code/wbia/dtool/sql_control.py", line 1016, in get_where
    **kwargs,
  File "/code/wbia/dtool/sql_control.py", line 1390, in executemany
    value = self.executeone(operation, params)
  File "/code/wbia/dtool/sql_control.py", line 1346, in executeone
    results = self.connection.execute(operation, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1090, in _execute_clauseelement
    keys = list(distilled_params[0].keys())
AttributeError: 'tuple' object has no attribute 'keys'
```

Problem resides within `get_where_eq`, because the parameters are
old-style tuple. And the query is build with '?' parameters. Backing
up to test this method outside the scope of `add_cleanly`.