Add "import utool" to dtool/_grave_depcache.py
Missing import reported when running doctests:

```
Traceback (most recent call last):
  File "/virtualenv/env3/lib/python3.6/site-packages/xdoctest/utils/util_import.py", line 187, in _custom_import_modpath
    module = import_module_from_name(modname)
  File "/virtualenv/env3/lib/python3.6/site-packages/xdoctest/utils/util_import.py", line 345, in import_module_from_name
    module = importlib.import_module(modname)
  File "/virtualenv/env3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/wbia/wildbook-ia/wbia/dtool/_grave_depcache.py", line 141, in <module>
    class AlgoRequest(BaseRequest, ut.NiceRepr):
NameError: name 'ut' is not defined
```