Wrap sql statement in text() in SQLDatabaseController._executeone_operation_fmt
```
DOCTEST TRACEBACK
Traceback (most recent call last):
  File "/virtualenv/env3/lib/python3.7/site-packages/xdoctest/doctest_example.py", line 598, in run
    exec(code, test_globals)
  File "<doctest:/wbia/wildbook-ia/wbia/dtool/depcache_control.py::DependencyCache.delete_root:0>", line rel: 7, abs: 1446, in <module>
    >>> depc.delete_root(root_rowids)
  File "/wbia/wildbook-ia/wbia/dtool/depcache_control.py", line 1454, in delete_root
    root_rowids, table_config_filter
  File "/wbia/wildbook-ia/wbia/dtool/depcache_control.py", line 1518, in get_allconfig_descendant_rowids
    op='AND',
  File "/wbia/wildbook-ia/wbia/dtool/sql_control.py", line 1018, in get_where_eq_set
    return self._executeone_operation_fmt(operation_fmt, fmtdict, **kwargs)
  File "/wbia/wildbook-ia/wbia/dtool/sql_control.py", line 1367, in _executeone_operation_fmt
    return self.executeone(operation, params, eager=eager, **kwargs)
  File "/wbia/wildbook-ia/wbia/dtool/sql_control.py", line 1414, in executeone
    "'operation' needs to be a sqlalchemy textual sql instance "
TypeError: 'operation' needs to be a sqlalchemy textual sql instance see docs on 'sqlalchemy.sql:text' factory function; 'operation' is a '<class 'str'>'
DOCTEST REPRODUCTION
CommandLine:
    pytest /wbia/wildbook-ia/wbia/dtool/depcache_control.py::DependencyCache.delete_root:0
```