Fix unstable/orig_graph_iden.py tests
Update `default:proot` in `OrigAnnotInference` tests to `vsmany` and
`default:pipeline_root` to `vsmany` because that's the only valid value.

```
  File "/wbia/wildbook-ia/wbia/algo/Config.py", line 714, in make_feasible_
    query_cfg._valid_pipeline_roots,
AssertionError: invalid pipeline root 'BC_DTW' valid roots are ['vsmany']
DOCTEST REPRODUCTION
CommandLine:
    pytest /wbia/wildbook-ia/wbia/unstable/orig_graph_iden.py::OrigAnnotInference:2
```

```
AssertionError: invalid pipeline root 'vsone' valid roots are ['vsmany']
```