Activate virtualenv before install in dockerfile
When installing vtool without activating virtualenv, cmake fails:

```
    ERROR: Command errored out with exit status 1:
     command: /virtualenv/env3/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/ibeis/vtool/setup.py'"'"'; __file__='"'"'/ibeis/vtool/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /ibeis/vtool/
    Complete output (117 lines):
    Not searching for unused variables given on the command line.
    CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
    -- Configuring incomplete, errors occurred!
...
    ---------------------------
    --------------------------------
    -- Trying "Unix Makefiles" generator - success
    --------------------------------------------------------------------------------

    Configuring Project
      Working directory:
        /ibeis/vtool/_skbuild/linux-x86_64-3.6/cmake-build
      Command:
        cmake /ibeis/vtool -G 'Unix Makefiles' -DCMAKE_INSTALL_PREFIX:PATH=/ibeis/vtool/_skbuild/linux-x86_64-3.6/cmake-install -DPYTHON_EXECUTABLE:FILEPATH=/virtualenv/env3/bin/python3 -DPYTHON_VERSION_STRING:STRING=3.6.9 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.6m -DPYTHON_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libpython3.6m.so -DSKBUILD:BOOL=TRUE -DCMAKE_MODULE_PATH:PATH=/virtualenv/env3/lib/python3.6/site-packages/skbuild/resources/cmake -DCMAKE_BUILD_TYPE:STRING=Release

    Traceback (most recent call last):

    ----------------------------------------
  Rolling back uninstall of vtool-ibeis
  Moving to /virtualenv/env3/lib/python3.6/site-packages/vtool_ibeis-2.1.1.dist-info/
   from /virtualenv/env3/lib/python3.6/site-packages/~tool_ibeis-2.1.1.dist-info
  Moving to /virtualenv/env3/lib/python3.6/site-packages/vtool_ibeis/
   from /virtualenv/env3/lib/python3.6/site-packages/~tool_ibeis
ERROR: Command errored out with exit status 1: /virtualenv/env3/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/ibeis/vtool/setup.py'"'"'; __file__='"'"'/ibeis/vtool/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

Activating the virtualenv before installing fixes this problem.