Fix web/apis_query.py::query_chips_simple_dict:1 test
The first traceback was:

```
DOCTEST TRACEBACK
Traceback (most recent call last):
  File "/virtualenv/env3/lib/python3.6/site-packages/xdoctest/doctest_example.py", line 556, in run
    exec(code, test_globals)
  File "<doctest:/wbia/wildbook-ia/wbia/web/apis_query.py::query_chips_simple_dict:1>", line rel: 9, abs: 102, in <module>
    >>> web_port = ibs.get_web_port_via_scan()
NameError: name 'ibs' is not defined
```

I changed the test to use `opendb_bg_web` instead of `opendb_in_background` to
get rid of the code to wait for the server to be up.  Also use
`send_wbia_request` instead of `requests`.

The second error:

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">                                                                                            <title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>
```

The url needs to be changed to `/api/query/chip/dict/simple/` from
`/api/query/chip/simple/dict/`.

The third traceback:

```
Traceback (most recent call last):
  File "/wbia/wildbook-ia/wbia/control/controller_inject.py", line 590, in translate_wbia_webcall
    output = func(ibs=ibs, **kwargs)
  File "/wbia/wildbook-ia/wbia/web/apis_query.py", line 109, in query_chips_simple_dict
    return ibs.query_chips(*args, **kwargs)
  File "/wbia/wildbook-ia/wbia/web/apis_query.py", line 1290, in query_chips
    assert daid_list is not None, 'do not specify daids and qreq'
AssertionError: Need to specify daids
```

Add `daid_list=[1, 2, 3]` to the argument to get the test to work.