Remove deprecated arguments from add_images_json test
```
DOCTEST TRACEBACK
Traceback (most recent call last):
  File "/virtualenv/env3/lib/python3.6/site-packages/xdoctest/doctest_example.py", line 556, in run
    exec(code, test_globals)
  File "<doctest:/wbia/wildbook-ia/wbia/web/apis_json.py::add_images_json:0>", line rel: 34, abs: 389, in <module>
    >>> gid_list = wbia.web.apis_json.add_images_json(web_instance, **_payload)
  File "/wbia/wildbook-ia/wbia/web/apis_json.py", line 479, in add_images_json
    % (bad_list,)
ValueError: This API signature has changed, the following parameters have been deprecated: ['image_uuid_list', 'image_width_list', 'image_height_list'].  Please remove them and try again.
DOCTEST REPRODUCTION
CommandLine:
    pytest /wbia/wildbook-ia/wbia/web/apis_json.py::add_images_json:0
/wbia/wildbook-ia/wbia/web/apis_json.py:389: ValueError
============================================================= short test summary info =============================================================
FAILED wbia/web/apis_json.py::add_images_json:0
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
======================================= 1 failed, 647 passed, 592 skipped, 5 warnings in 1337.95s (0:22:17) =======================================
```