Don't use cmake 3.18.2 when building wheel
Our macos build has been failing since 2020-08-21:

```
+ pip wheel . -w /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibuildwheelvcmdx5mi/built_wheel --no-deps
Processing /Users/runner/work/wildbook-ia/wildbook-ia
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /private/tmp/cibw_bin/python /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-srqflxar/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=42' wheel 'setuptools_scm[toml]>=3.4' scikit-build cmake ninja
       cwd: None
  Complete output (23 lines):
  Collecting setuptools>=42
    Downloading setuptools-49.6.0-py3-none-any.whl (803 kB)
  Collecting wheel
    Downloading wheel-0.35.1-py2.py3-none-any.whl (33 kB)
  Collecting setuptools_scm[toml]>=3.4
    Downloading setuptools_scm-4.1.2-py2.py3-none-any.whl (27 kB)
  Collecting scikit-build
    Downloading scikit_build-0.11.1-py2.py3-none-any.whl (72 kB)
  Collecting cmake
    Downloading cmake-3.18.2.tar.gz (28 kB)
      ERROR: Command errored out with exit status 1:
       command: /private/tmp/cibw_bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-install-iy6chcw0/cmake/setup.py'"'"'; __file__='"'"'/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-install-iy6chcw0/cmake/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-pip-egg-info-4z_omqj3
           cwd: /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-install-iy6chcw0/cmake/
      Complete output (5 lines):
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-install-iy6chcw0/cmake/setup.py", line 7, in <module>
          from skbuild import setup
      ModuleNotFoundError: No module named 'skbuild'
      ----------------------------------------
```

cmake 3.18.2 was released on 2020-08-21 and that appears to break the macos
build.