Fix unstable/scorenorm.py tests
Update `get_global_species_scorenorm_cachedir` test to import
`get_global_species_scorenorm_cachedir` instead of as a `IBEISController`
method.

```
DOCTEST TRACEBACK
Traceback (most recent call last):

  File "/virtualenv/env3/lib/python3.6/site-packages/xdoctest/doctest_example.py", line 556, in run
    exec(code, test_globals)

  File "<doctest:/wbia/wildbook-ia/wbia/unstable/scorenorm.py::get_global_species_scorenorm_cachedir:0>", line rel: 7, abs: 264, in <module>
    >>> species_cachedir = ibs.get_global_species_scorenorm_cachedir(species_text, ensure)

AttributeError: 'IBEISController' object has no attribute 'get_global_species_scorenorm_cachedir'
DOCTEST REPRODUCTION
CommandLine:
    pytest /wbia/wildbook-ia/wbia/unstable/scorenorm.py::get_global_species_scorenorm_cachedir:0
```